# Stage 1: Build
FROM golang:latest AS builder 

WORKDIR /app

# Copy go mod and sum files first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy entire source
COPY . .

# Build binary
RUN CGO_ENABLED=0 GOOS=linux go build -o chat-api ./cmd/api

# Stage 2: Runtime
FROM debian:bullseye-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y ca-certificates tzdata && \
    rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Bangkok

# ✅ Copy built binary
COPY --from=builder /app/chat-api .

# ✅ Copy config folder (ตรง path จริง)
COPY --from=builder /app/pkg/configs ./pkg/configs

# ✅ Declare build arguments
ARG PORT
ARG ENV
ARG BASE_URL
ARG FRONTEND_URL
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_SSL_MODE
ARG DB_TIMEZONE
ARG JWT_SECRET
ARG JWT_ACCESS_EXPIRY
ARG JWT_REFRESH_EXPIRY
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG CLOUDINARY_UPLOAD_FOLDER
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG REDIS_DB

# ✅ Set environment variables from build args
ENV PORT=${PORT}
ENV ENV=${ENV}
ENV BASE_URL=${BASE_URL}
ENV FRONTEND_URL=${FRONTEND_URL}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}
ENV DB_SSL_MODE=${DB_SSL_MODE}
ENV DB_TIMEZONE=${DB_TIMEZONE}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY}
ENV JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}
ENV CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV CLOUDINARY_UPLOAD_FOLDER=${CLOUDINARY_UPLOAD_FOLDER}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_DB=${REDIS_DB}

RUN mkdir -p /app/uploads

EXPOSE 8080

CMD ["./chat-api"]
